### ISSUE TITLE
Update ReadMe avec modularisation

### ISSUE THREAD

**Issue by marota** [BDonnot/ChroniX2Grid#25]
S'assurer que les readme est à jour dans les arguments des CLIs.
Faire une section mettant en avant la modularisation: 

- petit schema montrant que différents modules s'enchainent possiblement dans le calcul 
- paragraphe sur la possibilité d'interfacer son propre modèle
- un exemple

**Comment by NMegel** [comment]
README has been updated with loss, interfacing and submodules presentation
a965116e848445019cf797a6533757b55bf06799
