### ISSUE TITLE
Improve readibility and modularity of parameters.json

### ISSUE THREAD

**Issue by marota** [BDonnot/ChroniX2Grid#28]
All parameters of all models (wind, solar, thermal) are mixed into parameters.json, while they are relatively independant. We should improve the readilbility and ideally the modularity of that

**Comment by NMegel** [comment]
Done in 5eeefc39bb58e72cd540dad080c5834fa7b84dd6

Independent settings are available in params.json (general) params_res.json, params_load.json, params_loss.json, params_opf.json.
Choice of parser and backend is made in constants.py (ex: RENEWABLE_GENERATION_CONFIG = ResConfigManagerGan)
