### ISSUE TITLE
Losses adjustement in multi-core with Grid2Op

### ISSUE THREAD

**Issue by marota** [BDonnot/ChroniX2Grid#34]
When running multi-core, the losses computation seems to be the same for every scenarios computed in parallel (size observations.npz of 52.3Mo for example below). At the time of loss computation, a chronic folder is temporarily created in the original environment and loaded with grid2op.
But what if 3 chronic folder have to be temporarily loaded? Do they delete one another? Do grid2op run on the proper scenario and not the first one it finds ?

``
chronix2grid                          --mode LRT --output-folder Chronix2gridPath/output_data --input-folder Chronix2gridPath/getting_started/example/input --ignore-warnings                          --weeks 4 --case case118_l2rpn_wcci --n_scenarios 3 --nb_core 3 --scenario_name january --start-date 2012-01-01                          --seed-for-loads 912206665 --seed-for-res 912206665 --seed-for-dispatch 912206665
``

**Comment by NMegel** [comment]
[input_data.zip](https://github.com/BDonnot/ChroniX2Grid/files/6304280/input_data.zip)

In commit 4f87b5ecf15e5ec2016d579ab7d85ddce258c9ad we fixed this issue by
* Splitting the temporary folders by scenario, so they are independent
* Removing them at the end of multiprocessing only

To test, you can launch chronix2grid on this zip file
python -m chronix2grid.main --mode LRT --n_scenarios 3 --input-folder "absolute/input_data" --case case118_l2rpn_neurips_1x

All tests still pass

**Comment by marota** [comment]
The losses are apparently not coherent with the scenario:
![image](https://user-images.githubusercontent.com/5496312/114695258-b4ec6080-9d1b-11eb-950d-8fcae32d1920.png)

They are all computed on the first one...

**Comment by marota** [comment]
Also we should remove this big loss_simulation folder (it should not be necessary to save logs with the latests verison of grid2op) in the end, and only keep one log file "losses_adjustement.csv" (same as prod_p.csv, with deltas after loss adjustement. It will mainly be all zeros except for slack in our case for now)

**Comment by NMegel** [comment]
It was the using the write scenario but I agree that the folder names were ambiguous.
We made an evol in commit 9c3367a024700eb316c1dcace64d42b6f9aef7fb : now we don't write EpisodeData anymore by using run_detailed so that we don't need loss_simulation folders anymore

**Comment by marota** [comment]
It would still be useful to know about the losses that have been adjusted.
Can you log one file "losses_adjustement.csv" ? Maybe simply one column with rows as timestep, and the value of loss adjustement per timestep (as opposed to what I said before)
.

**Comment by NMegel** [comment]
Yes, done in commit 2c0415f00ba65d52ab6a2089fd8596ce90b912e2
It is written in the scenario output folder with the other chronics
You will see in particular that the adjusted loss are different between scenarios

**Comment by marota** [comment]
Nice, just compress it in bz2 as other files

**Comment by NMegel** [comment]
Yes done in 3e29ac4d1ee0181c8ce173ffb582bfe9360db51c
